"""Observe original upload acceptance, file publication and repeated execution."""

import hashlib
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from types import SimpleNamespace
from typing import cast

import pytest
from huggingface_hub import CommitOperationAdd
from huggingface_hub import CommitOperationDelete
from huggingface_hub import HfApi

from spotify_manager.routines import upload_library_files as upload
from tests.support.effects import Json
from tests.support.effects import encode_value


@dataclass(frozen=True)
class UploadScenario:
    """Choose an original boundary and acceptance side.

    Args:
        stage: Original file or remote operation to interrupt.
        after: Fail after the boundary accepts its effect.
    """

    stage: str
    after: bool


def upload_scenarios() -> list[UploadScenario]:
    """Enumerate publication and cleanup failures.

    Returns:
        Original cases in stable order.
    """
    stages = ("normal", "list", "commit", "url", "write", "replace", "stale", "cleanup")
    result = []
    for stage in stages:
        for after in (False, True):
            result.append(UploadScenario(stage, after))
    return result


class UploadMemory:
    """Record exact upload requests and accepted remote operations.

    Args:
        scenario: Original interruption profile.
    """

    def __init__(self, scenario: UploadScenario) -> None:
        self.scenario = scenario
        self.events: list[object] = []
        self.accepted: list[object] = []
        self.failed = False

    def fail(self, stage: str, after: bool) -> None:
        """Interrupt exactly one selected acceptance boundary.

        Args:
            stage: Observed boundary.
            after: Whether this observation follows acceptance.

        Raises:
            OSError: The selected original boundary is interrupted.
        """
        if self.failed or self.scenario != UploadScenario(stage, after):
            return
        self.failed = True
        raise OSError("scripted upload interruption")

    def list_repo_files(self, **parameters: object) -> list[str]:
        """Observe the original remote read before local materialization.

        Args:
            parameters: Original repository, revision and kind.

        Returns:
            Existing current, obsolete and unrelated remote files.
        """
        self.events.append(["list", parameters])
        self.fail("list", False)
        self.fail("list", True)
        prefix = upload.REMOTE_FILES_DIR + "/"
        return [
            prefix + upload.LASTFM_PART_PREFIX + "aa",
            prefix + upload.LASTFM_PART_PREFIX + "zz",
            "unrelated",
        ]

    def create_commit(
        self,
        *,
        operations: list[CommitOperationAdd | CommitOperationDelete],
        **parameters: object,
    ) -> SimpleNamespace:
        """Record operations and optional accepted-commit failure.

        Args:
            operations: Original ordered add/delete manifest.
            parameters: Original repository and commit message.

        Returns:
            Original commit metadata or selected malformed URL.
        """
        manifest = encode_value(operations, Path("/tmp"))
        self.events.append(["commit", parameters, manifest])
        self.fail("commit", False)
        self.accepted.append(manifest)
        self.fail("commit", True)
        url = None if self.scenario.stage == "url" else "https://example.test/commit"
        return SimpleNamespace(commit_url=url)


ACTIVE: UploadMemory | None = None
WRITE = Path.write_bytes
REPLACE = Path.replace
UNLINK = Path.unlink


def write_part(path: Path, content: bytes) -> int:
    """Record temporary writes while preserving native acceptance.

    Args:
        path: Original hidden temporary file.
        content: Original generated bytes.

    Returns:
        Accepted byte count.
    """
    assert ACTIVE is not None
    ACTIVE.events.append(["write", path.name, content.decode("ascii")])
    ACTIVE.fail("write", False)
    count = WRITE(path, content)
    ACTIVE.fail("write", True)
    return count


def replace_part(path: Path, target: Path) -> Path:
    """Record accepted atomic replacement.

    Args:
        path: Original temporary file.
        target: Original final part.

    Returns:
        Published target path.
    """
    assert ACTIVE is not None
    ACTIVE.events.append(["replace", path.name, target.name])
    ACTIVE.fail("replace", False)
    result = REPLACE(path, target)
    ACTIVE.fail("replace", True)
    return result


def unlink_part(path: Path, missing_ok: bool = False) -> None:
    """Record obsolete deletion and temporary cleanup separately.

    Args:
        path: Original managed file.
        missing_ok: Original missing-file policy.
    """
    assert ACTIVE is not None
    stage = "cleanup" if path.name.startswith(".") else "stale"
    ACTIVE.events.append([stage, path.name, missing_ok])
    ACTIVE.fail(stage, False)
    UNLINK(path, missing_ok=missing_ok)
    ACTIVE.fail(stage, True)


def files_snapshot(root: Path) -> dict[str, str]:
    """Observe retained files through deterministic content hashes.

    Args:
        root: Isolated original managed directory.

    Returns:
        Every surviving file, including partial temporary files.
    """
    result = {}
    for path in sorted(root.iterdir()):
        result[path.name] = hashlib.sha256(path.read_bytes()).hexdigest()
    return result


def attempt(plan: upload.LibraryFilesUploadPlan, memory: UploadMemory) -> object:
    """Record original success or translated/native failure.

    Args:
        plan: Original upload plan.
        memory: Recorded external boundaries.

    Returns:
        Original result or error and explicit cause.
    """
    try:
        return upload.upload_library_files(plan, api=cast(HfApi, memory))
    except (upload.LibraryFilesUploadError, OSError) as error:
        return {
            "error": type(error).__name__,
            "message": str(error),
            "cause": type(error.__cause__).__name__ if error.__cause__ else None,
        }


def observe_upload(
    scenario: UploadScenario,
    root: Path,
    run: Callable[[upload.LibraryFilesUploadPlan, UploadMemory], object] = attempt,
) -> Json:
    """Capture initial execution and retry after each original boundary failure.

    Args:
        scenario: Original selected boundary.
        root: Isolated managed directory.

    Returns:
        Original outcomes, events and accepted local/remote state.
    """
    global ACTIVE
    memory = UploadMemory(scenario)
    ACTIVE = memory
    plan = seed_plan(root)
    outcomes = []
    with pytest.MonkeyPatch.context() as patch:
        patch.setattr(Path, "write_bytes", write_part)
        patch.setattr(Path, "replace", replace_part)
        patch.setattr(Path, "unlink", unlink_part)
        for _ in range(2):
            outcomes.append([run(plan, memory), files_snapshot(root)])
    ACTIVE = None
    return encode_value(
        {"outcomes": outcomes, "events": memory.events, "accepted": memory.accepted},
        root,
    )


def seed_plan(root: Path) -> upload.LibraryFilesUploadPlan:
    """Seed two generated parts and every original obsolete fallback family.

    Args:
        root: Isolated managed directory.

    Returns:
        Original prepared source and two-part manifest.
    """
    source = root / upload.YOUR_LIBRARY_FILENAME
    source.write_text('{"tracks": []}')
    for name in (
        upload.LASTFM_PART_PREFIX + "zz",
        upload.LASTFM_COMPRESSED_FILENAME,
        upload.LASTFM_BINARY_PART_PREFIX + "aa",
    ):
        (root / name).write_bytes(b"obsolete")
    parts = []
    for suffix in ("aa", "ab"):
        name = upload.LASTFM_PART_PREFIX + suffix
        parts.append(
            upload.GeneratedPart(
                root / name,
                upload.REMOTE_FILES_DIR + "/" + name,
                suffix.encode("ascii"),
            )
        )
    resource = upload.UploadResource(
        source.name,
        source,
        upload.REMOTE_FILES_DIR + "/" + source.name,
        0,
        source.stat().st_size,
    )
    return upload.LibraryFilesUploadPlan("repo", "main", (resource,), tuple(parts))
